### ISSUE TITLE
Getting Started guide

### ISSUE THREAD

**Issue by westonbelk** [CUCyber/cucyber.github.io#15]
Create a page (under Useful Resources most likely) that goes over the basics of installing a pen testing distro in a virtual machine and other introductory topics. 

- [ ] Installing a pen testing distro
- [ ] Networking basics
- [ ] Information gathering basics (nmap, what a cve is)

Benefits: New members who are eager to learn, but don't want to wait a month and 4 meetings to do so. We also have a page to point people to when they are having trouble installing Kali

Definitely want opinions on what kind of information should go in here and if this will actually benefit us

**Comment by lilyinstarlight** [comment]
Yeah, definitely installing Kali and basic usage. Enough to get them setup to follow the presentations.

**Comment by Kyle-Wolfe** [comment]
It would be nice to see an overview of what all of the tools covered in the presentations are, just enough to get them installed and what they are used for.

**Comment by nbulischeck** [comment]
If this could start in the near future, that would be great

**Comment by lilyinstarlight** [comment]
Superseded by CUCyber/wiki#1.
