### ISSUE TITLE
Use Jekyll templating

### ISSUE THREAD

**Issue by westonbelk** [CUCyber/cucyber.github.io#21]
Use Jekyll static site generation to create templates for parts of the site. Will ease with modifying parts of the site everywhere at once. Jekyll has automatic integration with Github so there's no additional build step.

**Comment by nbulischeck** [comment]
**by the end of the summer**

wya

**Comment by westonbelk** [comment]
Development on this is currently in the dev branch. The content in the branch is stale at this point and needs to be updated to reflect the current state of master. I don't know how feasible an automatic merge would be so I would consider manual merging.
