### ISSUE TITLE
Navigation Bar Redundancy

### ISSUE THREAD

**Issue by cyntheticfox** [CUCyber/cucyber.github.io#30]
Having both a site top link in the top left (the CU Cyber name and logo) and a "home" navigation bar option that point to the same page is redundant

**Comment by lilyinstarlight** [comment]
https://nohome.dev.cucyber.net/ vs https://dev.cucyber.net/

**Comment by cyntheticfox** [comment]
The nohome branch looks good to me, but I'd recommend a second opinion
