### ISSUE TITLE
About Page Formatting

### ISSUE THREAD

**Issue by cyntheticfox** [CUCyber/cucyber.github.io#31]
The mid-size layout of the about page results in a large whitespace gap between the treasurer and previous position

![image](https://user-images.githubusercontent.com/17628961/79040950-15513b00-7bba-11ea-9a0e-598acdedca68.png)

**Comment by cyntheticfox** [comment]
seems to be a byproduct of 15px padding on each side. Can be fixed by reducing the scaling, but seems cramped then. Might recommend going to 2-wide.

**Comment by lilyinstarlight** [comment]
GMaps isn't responsive either so I just made it so that when it hits the `md` size, 'Meet the Officers' and 'Find Us...' are stacked vertically and the officers are 2x3 (instead of 3x2) until you hit `sm` when everything goes vertical (like before).
