### ISSUE TITLE
Calendar Element on events.html does not Scale

### ISSUE THREAD

**Issue by cyntheticfox** [CUCyber/cucyber.github.io#32]
The calendar element on the `events.html` page is set to a fixed size of 1200x500. These should be adjusted to relative elements to allow for both padding on the sides, as well as to allow the calendar to scale for smaller displays.

**Comment by lilyinstarlight** [comment]
I don't think we're going to make GCal responsive (i.e. scale very well) without an external library. Some nice libraries do exist so evaluating those is probably the best option.
