### ISSUE TITLE
Add page for upcoming events and next meeting topics (same page)

### ISSUE THREAD

**Issue by mbinns** [CUCyber/cucyber.github.io#6]
Please add a page for events that are upcoming and the tasks that need to be done before that date

Also have a location, possibly a side bar about next meeting topic

**Comment by mbinns** [comment]
The blog pages would probably work well for this

**Comment by lilyinstarlight** [comment]
@klsimps I'm happy to help you with this anytime you'd like. I'm thinking following the blog style for this template would be easiest, though I'll have to modify it of course to better represent our events.

**Comment by lilyinstarlight** [comment]
See #14
