### ISSUE TITLE
Update copyright

### ISSUE THREAD

**Issue by MEhrn00** [CUCyber/cucyber.github.io#64]
Currently the copyright for https://cucyber.net says `Copyright: 2020 CU Cyber` the year needs to be updated to `Copyright: 2021 CU Cyber`. This should not be too much of an issue; however, the out of date copyright makes the site look not well maintained.

**Comment by MEhrn00** [comment]
Reopening this issue. Can you make a PR so that we can have this on the main site? @lucario

**Comment by lucario** [comment]
My bad I forgot to actually check which branch this was being built from, resolved in #66
