### ISSUE TITLE
Add a page for the hack pack

### ISSUE THREAD

**Issue by mbinns** [CUCyber/cucyber.github.io#7]
Figure out how we can embed a live copy of our hack pack in a page

**Comment by lilyinstarlight** [comment]
I'll see about Pandoc's HTML generation. I'm going to move the hard part of this issue to CUCyber/hackpack#75 for better tracking.

**Comment by lilyinstarlight** [comment]
We'll need to fix a few more issues here before we can go live with the HTML hackpack.

- [x] Make inline code do line breaks
- [x] Fix anchors going too far when accounting for the header
